version: "2"


services:
  densenet:
    build:
      context: ./densenet
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      - MINIO_SERVER_ACCESS_KEY=minio-access-key
      - MINIO_SERVER_SECRET_KEY=minio-secret-key
  stardist:
    build:
      context: ./stardist
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    expose:
      - "8080"
    environment:
      - MINIO_SERVER_ACCESS_KEY=minio-access-key
      - MINIO_SERVER_SECRET_KEY=minio-secret-key
  interface:
    build:
      context: ./interface
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8082:8080"
    expose:
      - "8080"
    environment:
      - MINIO_SERVER_ACCESS_KEY=minio-access-key
      - MINIO_SERVER_SECRET_KEY=minio-secret-key
  minio:
    image: 'bitnami/minio:latest'
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=minio-root-user
      - MINIO_ROOT_PASSWORD=minio-root-password
    volumes:
      - ./minio:/data
